<?php

/**
 * PluginsbVideoWithImageSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbVideoWithImageSlotTable extends aVideoSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbVideoWithImageSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbVideoWithImageSlot');
    }
}