<?php

/**
 * PluginsbMicrodataPostalAddressSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbMicrodataPostalAddressSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbMicrodataPostalAddressSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbMicrodataPostalAddressSlot');
    }
}