<?php

/**
 * PluginsbApostropheFAQSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbFAQSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbApostropheFAQSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbFAQSlot');
    }
}