<?php

/**
 * PluginsbApostropheJQueryUITabbedContentSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbApostropheJQueryUITabbedContentSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbApostropheJQueryUITabbedContentSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbApostropheJQueryUITabbedContentSlot');
    }
}