<?php

/**
 * PluginsbJQueryCountdownTimerSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbJQueryCountdownTimerSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbJQueryCountdownTimerSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbJQueryCountdownTimerSlot');
    }
}