<?php

/**
 * PluginsbCampaignMonitorSubscribeSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbCampaignMonitorSubscribeSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbCampaignMonitorSubscribeSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbCampaignMonitorSubscribeSlot');
    }
}